import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header";
import { SocketProvider } from "@/context/socket-context";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Talk to me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={rubik.className}>
        <SocketProvider>
          <Header />
          {children}
        </SocketProvider>
      </body>
    </html>
  );
}
